# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 115c82095d39e7733b0d09705f57704ac30522f86798236336b514b40bee2099e5b87c896af957a24e0a6cc244996058a142e27ff4630135193c1bc6700a3771

test:
  secret_key_base: c920a3b8a56b52de974b6f73fa15b5f8d958c7627dde0a5873cec64c3eaf372274cd71611596e24d5979431a0605ac007f80b849256ad2d54faa4c2f8e8719a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
